name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19.0-rc.2]
    env:
      VERBOSE: 1

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Install tparse
      run: go install github.com/mfridman/tparse@latest

    - name: Test
      run: go test -race -count=1 -timeout 30s -coverprofile=coverage.txt -covermode=atomic  -json ./... | tparse -all -follow
